include:
  - board: xiao_ble
    shield: totem_dongle
    snippet: studio-rpc-usb-uart
    cmake-args:
      - -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: totem_left
    cmake-args:
      - -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: xiao_ble
    shield: totem_right
    cmake-args:
      - -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: xiao_ble
    shield: settings_reset
